# Generated by Django 2.2.1 on 2019-05-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predict',
            old_name='user',
            new_name='username',
        ),
    ]
