# Generated by Django 2.2.1 on 2019-05-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_auto_20190523_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='accuracy',
            field=models.FloatField(default=0.0, max_length=4),
            preserve_default=False,
        ),
    ]
